version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"